# Generated by Django 5.0.6 on 2024-05-09 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
