# Generated by Django 5.0.6 on 2024-05-08 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
