# Generated by Django 5.0.6 on 2024-05-09 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_rename_update_at_brand_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
